language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - python -m pytest --cov-branch --cov=code code/flake_master/tests
after_success:
  - bash <(curl -s https://codecov.io/bash)